# Generated by Django 3.1.2 on 2020-10-18 14:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nkdsu_id', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True)),
                ('artist', models.TextField(blank=True)),
                ('role', models.TextField(blank=True)),
                ('certificate', models.FileField(upload_to='')),
                ('certified_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('certified_show_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
